# Generated by Django 3.1.4 on 2021-01-15 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager_app', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
